# Generated by Django 5.0.1 on 2024-01-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_from_real_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='from_real_news',
            name='img',
            field=models.URLField(default=''),
        ),
    ]
